### ISSUE TITLE
Should a dead bunny look selected in the Pedigree view?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#102]
When a bunny dies, it disappears from the environment view.  If the bunny was selected and appears in the Pedigree view, should the blue selection rectangle around the bunny persist in the Pedigree view?  Or should the selection rectangle disappear?   

Here's an example. Should the blue rectangle go away when the selected bunny dies?

<img width="682" alt="screenshot_388" src="https://user-images.githubusercontent.com/3046552/84322598-794c9d00-ab32-11ea-97c2-d8ef0944fa51.png">

**Comment by amanda-phet** [comment]
I think the blue rectangle should stay, because it is indicating that you're viewing a selected bunny. If you don't see a blue rectangle in the environment view, and you see a big red x, then it's clear that bunny died. The blue rectangle is nice, to me, because it shows the focus of the pedigree and directs your attention to that bunny first. We want users reading it "bottom up" in a sense.

**Comment by pixelzoom** [comment]
Sounds good. Nothing needs to be changed, so closing.
