### ISSUE TITLE
uninstrument BunnyNode and WolfNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#124]
In https://github.com/phetsims/natural-selection/issues/60#issuecomment-656320887, we decided that the view for bunnies and wolves (BunnyNode and WolfNode) does not need to be instrumented.  And in fact cannot be instrumented once we move to more high-performance sprite rendering.   So I will uninstrument.

**Comment by pixelzoom** [comment]
Instrumentation for BunnyNode and WolfNode was removed in the above commit.  This also involved removing 2 PhetioGroups, 2 IO types, and some supporting files.   So lots of code removed.

@amanda-phet please verify that this looks OK in Studio.  You can compare [1.0.0-dev.66](https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.66/phet-io/) (before) and [1.0.0-dev.67](https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.67/phet-io/) (after).

**Comment by pixelzoom** [comment]
Raising performance to "high", because this is going to be very difficult to revert as I move forward.

**Comment by amanda-phet** [comment]
I still see the individual bunnies and wolves in the model. Does that mean they are still instrumented? Because it seems like all of that information is still there. I'm looking at `naturalSelection.labScreen.model.bunnyCollection.bunnyGroup` and `naturalSelection.labScreen.model.wolfCollection.wolfGroup`. 

I am still fine with the changes made, but I guess I'm curious how the bunnies and wolves were un-instrumented if I can still see an element for each bunny, such as `naturalSelection.labScreen.model.bunnyCollection.bunnyGroup.bunny_1`.

**Comment by pixelzoom** [comment]
The view was uninstrument, the model is unchanged. From https://github.com/phetsims/natural-selection/issues/124#issuecomment-656397594:
> Specifically, `naturalSelection.labScreen.view.environmentNode.bunnyNodeCollection` and `naturalSelection.labScreen.view.environmentNode.wolfNodeCollection` are gone.

**Comment by amanda-phet** [comment]
Yes I saw the comment and verified that they are gone from the view, but was curious if it's an issue that individual bunnies are still present in the model. I don't really understand it all, but I can close the issue since it seems that un-instrumenting the nodes was the goal.
