### ISSUE TITLE
Line missing next to Total checkbox

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/natural-selection#144]
This black horizontal line disappeared between dev.53 and dev.54. 

![image](https://user-images.githubusercontent.com/7852916/88833079-f5587e00-d18e-11ea-91e0-8f1d4d6f1742.png)

**Comment by pixelzoom** [comment]
A color constant was renamed, and the rename didn't get refactored for the Total checkbox. Thank you WebStorm and JavaScript! 

Fixed in master.  Closing.

<img width="258" alt="screenshot_443" src="https://user-images.githubusercontent.com/3046552/88834695-7284f280-d191-11ea-9a57-cde21d76a356.png">
