### ISSUE TITLE
The cancel mutation button is hard to press on a touch device

### ISSUE THREAD

**Issue by phet-steele** [phetsims/natural-selection#148]
Removing pending mutations is sometimes quite difficult on a touch screen. I think we can certainly afford to dilate the pointer areas of the "x", and probably should do so before prototype release:

![image](https://user-images.githubusercontent.com/5863899/88982277-126f7880-d285-11ea-82aa-86f4236183b5.png)

Seen on Win 10 Chrome 84.0.4147.89. For phetsims/QA/issues/522.

<details>
<summary>Troubleshooting Information</summary>

Name: ‪Natural Selection‬
URL: https://phet-dev.colorado.edu/html/natural-selection/1.0.0-rc.1/phet/natural-selection_all_phet.html?showPointerAreas
Version: 1.0.0-rc.1 2020-07-29 19:13:57 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
Language: en-US
Window: 1456x923
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
</details>

**Comment by pixelzoom** [comment]
Agreed. But none of the pointer areas in this sim have been optimized yet.

**Comment by pixelzoom** [comment]
Agreed. But none of the pointer areas in this sim have been optimized yet.  That wasn't requested for the prototype. If it should be included in a prototype, then we should stop the RC now, because pointer optimizations is not something that I can cost-effectively patch into the RC branch. 

@amanda-phet your call.

**Comment by pixelzoom** [comment]
To clarify... If it's only these specific buttons that need to be addressed, I can patch that into the release branch.  But if this extends to other pointer areas, we should start over.

**Comment by pixelzoom** [comment]
Running with `?showPointerAreas`, it looks like all of the other pointer areas are reasonable. So we can probably get away with just doing these cancel buttons.   But again, @amanda-phet your call... options are:

(1) Do nothing for the protoype
(2) Expand touchArea for these cancel buttons only (requires patching release branch)
(3) Optimize all pointer areas for the prototype (requires starting RC over)

**Comment by pixelzoom** [comment]
And went ahead and did option (2), and patched it into the release branch.  I expanded both the touchArea and mouseArea, see screenshot below. We can refine this further when we get to the "optimize pointer areas" task in the sim checklist.  This should be more than fine for the prototype. 

@amanda-phet if you disagree, let me know.  Otherwise this is ready for testing in next RC.

<img width="236" alt="screenshot_447" src="https://user-images.githubusercontent.com/3046552/89000169-eddec500-d2b3-11ea-9778-9660c5f28867.png">

**Comment by pixelzoom** [comment]
@phet-steele feel free to test-drive this in master.  Let me know if you think this is fine for the prototype, or if they should be expanded more.

**Comment by phet-steele** [comment]
I tested this with https://phet-dev.colorado.edu/html/natural-selection/1.1.0-dev.3/phet/natural-selection_all_phet.html on a touch screen, and these buttons were very easy to press! Thanks.

**Comment by pixelzoom** [comment]
Since the next 1.0 RC is going to be a merge from master, and this has been verified in master, I'm closing this issue.
