### ISSUE TITLE
Change request: allow wolves to eat bunnies when there are < 6

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/natural-selection#152]
MH said:
>When there are only white rabbits in the desert, the wolves eventually eat all of them.  When there are brown only or white & brown, not all of the rabbits are eaten.   Is it intentional to have it be different for white vs white & brown populations?  The same issue happens in arctic – all brown rabbits get eaten but when only white rabbits, they don’t all get eaten. 

I discussed this with @pixelzoom and I'd like to change the rule so that if there are fewer than 5 bunnies *total*, wolves can eat them. Currently, we have a rule in place so that if there are just a few bunnies with the "desired" trait, wolves ignore them, but this is problematic when there aren't alternative bunnies to eat because they don't die, which seems unlikely in nature.

**Comment by amanda-phet** [comment]
@pixelzoom I can't remember if the current rule is <5 or ≤5, so whatever the rule is right now for ignoring bunnies with the fur color that matches the environment, please apply the same value to this case.

**Comment by pixelzoom** [comment]
The current rule is that the preferred bunnies are not eaten if their population is <= 5.     But that applies to the population of the preferred phenotype, not the total population.   This issue is dealing with the total population.  Do you really want to use the same value for both population limits?

**Comment by pixelzoom** [comment]
Discussed with @amanda-phet on Slack.   We decided to use <= 5.

<details>
<summary>Slack discussion</summary>

Amanda McGarry:spiral_calendar_pad:  1:57 PM
I was thinking we’d use the same value since that’s the point at which the rule “changes.” But now that I play out the scenarios, I think it needs to be lower. So perhaps if the total population is ≤4, the wolves will ignore the rule to ignore the brown bunnies (in the equator). What do you think?

Chris Malley  1:59 PM
I'm not sure.

Amanda McGarry:spiral_calendar_pad:  2:00 PM
Let’s go with 4 bunnies and I can see how it is. When I tried to imagine the different combinations of bunnies, I do think somewhere close to the threshold makes sense

Chris Malley  2:00 PM
I guess using the same value would be OK.  For example, at equator, wolves would eat all of the white bunnies first, but eventually get around to eating all of the brown bunnies.

Amanda McGarry:spiral_calendar_pad:  2:02 PM
exactly, that is the goal
so it seems natural to me to use the same value, but I’m fine with lower too

Chris Malley  2:03 PM
OK. Let's go with the same value then, so we're not introducing yet-another constant.
</details>

**Comment by pixelzoom** [comment]
The preferred phenotype is now ignored by wolves when the number of bunnies with that phenotype that would be eaten is <= 5 AND the total population is > 5.

Changed in master and 1.0 branch.  

@amanda-phet please verify in master or [1.1.0-dev.2](https://phet-dev.colorado.edu/html/natural-selection/1.1.0-dev.2/phet/natural-selection_en_phet.html). Please assign back to me after reviewing.

**Comment by amanda-phet** [comment]
This seems to be working perfectly!

**Comment by pixelzoom** [comment]
Excellent, thanks @amanda-phet.

Ready for testing in the next 1.0 (prototype) RC.

**Comment by pixelzoom** [comment]
@amanda-phet FYI... This is a "minimum population" constraint, and we have a few of these in the sim.  Some (like this one) were specified as <=, others were specified as <.   That made for some confusing and error-prone code.  So I have standardized them all to use <, and this constraint is now < 6.   I'll adjust the issue title to reflect this.

**Comment by pixelzoom** [comment]
Since the next RC is going to be published from master, I'm going to go ahead and close this issue.
