### ISSUE TITLE
Making "Bunnies take over the world" more representative of final condition

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/natural-selection#154]
Would it be possible to have the "bunnies take over the world" artwork have 3 possibilities?

1. All white
2. All brown
3. Mixture

I found it a little jarring seeing the population be for instance all white bunnies and then the depiction at the end be a mixture of white and brown. That is sort of the "final representation", so if you set up conditions (like white bunnies being recessive but wolves and the arctic environment) you pretty much get 100 percent white bunnies.

I think the argument could also be made that you would see some mixture regardless since the world has many environments, but I think for the purposes of the sim it would be cleaner to have 3 ending possibilities.

Not sure if these is a pretty easy change, or fairly involved. My naive sense would be 3 pieces of artwork and the appropriate one is chosen depending on the population at the final step. If 100% are white or brown, go with the pure white or pure brown picture, if anything else go with the mixed picture. 

@pixelzoom no action needed in the code, but could you let me know the difficulty

@amanda-phet curious for your thoughts.

**Comment by pixelzoom** [comment]
> @pixelzoom no action needed in the code, but could you let me know the difficulty

* The "world" image is easily the largest resource in this sim. Each image adds ~567KB to the html file.  Adding 2 more images will increate the total html file size ~2.5MB to ~3.6MB. (I tested this to confirm.). That's a pretty significant increase for this feature.  Providing the bunnies and world as a separate images would decrease the size a bit, but increase the code complexity.

* The dialog is currently created at startup so that we don't have to deal with it being a dynamic PhET-iO element.  We'll either need 3 different dialogs (one for each image) or a dialog whose image can be changed.  I'd probably go for the latter, even thought it's more complicated. 

* Determining which image to use is relatively easy -- just look at the bunny counts at the point when the dialog opens.

**Comment by amanda-phet** [comment]
I am 100% ok with leaving this image as it is. While I understand your desire (in fact, I think I brought this up early in the design process), I think the image clearly conveys the information and provides a cute all-purpose image.

**Comment by pixelzoom** [comment]
I'm going to move forward assuming that this would not be something that would need to be cherry-picked to the 1.0 (prototype) branch, and is likely to be closed as "do nothing".

**Comment by ariel-phet** [comment]
Going ahead and closing considering the complexities. We can revisit if we get teacher feedback or student confusion.
