### ISSUE TITLE
Do students understand the generation clock?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#162]
Look for understanding (or misunderstanding) of the following things related to the generation clock:

* 1 full cycle of the clock is 1 generation
* The clock "reveal" indicates how much of a generation has passed.
* How the icons to the right of the Environment Factors check boxes are related to the clock.
* The color-coded "slices" of the clock correspond to environmental factors.
* Limited Food and Tough Food share the same "slice" of the clock.

**Comment by amanda-phet** [comment]
Yes, students understood the generation clock- a full cycle, when mating occurred, and 2/3 easily interpreted the color-coded slices without assistance. While one called a cycle a "day", that could easily be cleared up in a classroom setting, especially since he could tell the x-axis of the population graph was Generations.
