### ISSUE TITLE
PhET-iO elements that should be read-only

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/natural-selection#181]
Found when completing #5

- [x] `naturalSelection.labScreen.view.graphs.proportionsNode.visibleProperty` 

- [x] `naturalSelection.labScreen.view.graphs.proportionsNode.proportionsGraphNode.earsColumn.endBarNode.mutantPercentageNode.textProperty`
- [x] `naturalSelection.labScreen.view.graphs.proportionsNode.proportionsGraphNode.earsColumn.endBarNode.normalPercentageNode.textProperty`
- [x] `naturalSelection.labScreen.view.graphs.proportionsNode.proportionsGraphNode.furColumn.endBarNode.mutantPercentageNode.textProperty`
- [x] `naturalSelection.labScreen.view.graphs.proportionsNode.proportionsGraphNode.furColumn.endBarNode.normalPercentageNode.textProperty`
- [x] `naturalSelection.labScreen.view.graphs.proportionsNode.proportionsGraphNode.teethColumn.endBarNode.mutantPercentageNode.textProperty`
- [x] `naturalSelection.labScreen.view.graphs.proportionsNode.proportionsGraphNode.teethColumn.endBarNode.normalPercentageNode.textProperty`

**Comment by pixelzoom** [comment]
Requests are addressed in the above commit.  

Re `*.endBarNode.normalPercentageNode` and `*.endBarNode.mutantPercentageNode`...  Rather than just make their `textProperty` read-only, I made those elements read-only.  This makes all of their child elements (including `textProperty`) read-only, which seemed appropriate.  The other child elements are:

`pickableProperty` - irrelevant because there are no listeners for these Nodes
`visibleProperty` - should be read-only because visibility is controlled via the "Values" checkbox
`opacityProperty` - I see no need to change this, and it will be going away someday

@amanda-phet please review in master or [1.1.0-dev.10](https://phet-dev.colorado.edu/html/natural-selection/1.1.0-dev.10/phet/natural-selection_en_phet.html).

**Comment by amanda-phet** [comment]
Reviewed. All of these look good.
