### ISSUE TITLE
credits

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#2]
Update credits in natural-selection-main.js.

**Comment by pixelzoom** [comment]
Credits in the design doc are:

> Amanda McGarry (lead designer)
Chris Malley (developer)
Megan Hoffman
Oliver Nix
Ariel Paul
Kathy Perkins

Credits in the Java version are:

<img width="544" alt="screenshot_1634" src="https://user-images.githubusercontent.com/3046552/67442494-3e572280-f5be-11e9-96ed-909bb2f47c3e.png">

PhET convention is to move the Java credits to "Team". So the HTML5 credits are initially:

<img width="800" alt="screenshot_1633" src="https://user-images.githubusercontent.com/3046552/67442431-0c45c080-f5be-11e9-8e9d-85150dbc3bbd.png">

**Comment by amanda-phet** [comment]
>PhET convention is to move the Java credits to "Team". 

Is this new? I am used to seeing original developers and designers listed in those respective categories, not put in the team. Looking at the recently published PhET sim ports, Gas Props follows this convention, but Blackbody, EFAC, Fractions Intro, Build a Fraction, do not. Curve Fitting similarly doesn't follow this convention. 

@ariel-phet can you clarify.

**Comment by pixelzoom** [comment]
I don't know what other developers have been doing.  But if I reuse or port parts of the Java sim, then I definitely list the original Java developer as "developer" because their code is part of the HTML5 implementation.  That was certainly the case in Gas Properties, specifically for collision detection.  That is not likely to be the case for Natural Selection.

**Comment by arouinfar** [comment]
@amanda-phet the Java version of Gas Properties does not explicitly credit anyone as the lead designer, which is why I'm the only lead listed in the HTLM5 credits. Generally speaking, I'm always co-listed with the Java lead in HTML5 credits.

@pixelzoom sounds like you intended to credit Ron LeMaster as a developer in Gas Props, but he is in the Team section of the credits.

**Comment by pixelzoom** [comment]
Hmm... I guess I did strictly follow the "move Java credits to team" policy.  I don't think Ron cares, I'll buy him a beer ;)

If someone wants to specify a different policy, please do and I'll follow it.  And if the checklist is being followed, there are multiple opportunities to adjust the credits before a sim is published.  That's why this issue exists.

**Comment by ariel-phet** [comment]
@pixelzoom @amanda-phet @arouinfar my understanding went something like this...

For ports, we list the original lead designer in the Lead Design, but generally if there have been significant changes, we put the HTML5 lead first. (So for instance, current Vector Addition lists Mike Dubson first in lead design, but probably Amy should be listed first there)

For software development, if the code is basically the same as the Legacy code, it seems correct to include the original software developer, but certainly recently, most of the code has basically been written from scratch. I think this is mostly developer discretion.

I cannot say I have personally been too worried as long as people are listed (but that is because I personally don't care about credits too much). But the above is my understanding of our decisions.

**Comment by pixelzoom** [comment]
Thanks @ariel-phet.

@amanda-phet @arouinfar let me know if you want to make changes to the "Lead Design" credit in Natural Selection and Vector Addition respectively. 

I'll decide on the "Software Development" credit when we see whether any of the Java implementation gets incorporated into the HTML5 version (so far not).

**Comment by pixelzoom** [comment]
I've added @phet-steele to the credits, for his role in testing the 1.0 (prototype) release.

**Comment by pixelzoom** [comment]
I've added @phet-steele to the credits, for his role in testing the 1.0 (prototype) release.

**Comment by pixelzoom** [comment]
@KatieWoe I've added Logan Bray to the QA credits, for his role in 1.2 RC testing.  (Unfortunately he will not appear in the 1.2 credits, but it's not a public release, it's just a link that's going to a client for temporary use.). Anyone else that I should add?

**Comment by KatieWoe** [comment]
I think Liam should be added as well.

**Comment by pixelzoom** [comment]
I've added Liam.

**Comment by pixelzoom** [comment]
Looks like I forgot to close this after publishing 1.2.  Closing.
