### ISSUE TITLE
Population graph should not display "Zoom out..." message when all checkboxes are unchecked

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#213]
Noticed with working on #209.  If none of the Population checkboxes are checked, then the graph is displaying nothing. In this case, it's not appropriate to display "Zoom out to show data", but we are.

This will not be addressed in the prototype RC.

**Comment by pixelzoom** [comment]
I addressed this in the above commit, which can be test-driven in [1.2.0-dev.1](https://phet-dev.colorado.edu/html/natural-selection/1.2.0-dev.1/phet/natural-selection_en_phet.html).  To test:

1. Run the sim
2. Go to ether screen
3. Zoom the Population graph in fully, so the y-axis range is [0,5]
4. Press the "Add a Mate" button.
5. Wait for bunnies to take over the world, close the dialog
6. Verify that "Zoom in to see data" appears in the graph
7. Toggle "Total" checkbox (and other checkboxes) off and on. Verify that "Zoom..." only appears in the graph when there is no data visible and at least 1 checkbox is checked.

**Comment by pixelzoom** [comment]
Assuming this tests OK, this will be picked up by the 1.1 prototype. #209 blocks the prototype, and this fix also fixes that issue.

**Comment by amanda-phet** [comment]
It seems to be working correctly! 

One thing I want documented: 

First, I have total and white fur checked (can just be one checkbox though). It looks like this:
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/7852916/91777851-2b35bb80-ebae-11ea-957c-ca4f537960fb.png">

Then when I click brown fur, the "zoom out" text goes away, but it's hard to tell that there is visible data for brown fur. 
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/7852916/91778098-c7f85900-ebae-11ea-8dba-b61d6280a436.png">

Just wanted this documented. Nothing is wrong, the code is correct, but it took me a few clicks to realize that there was data because it is subtle.

**Comment by pixelzoom** [comment]
Yes indeed, a horizontal line at y=0 is easy to miss. The only way around this would be to make the line thicker _for all plotted data_, which I think would compromise the overall look of the graph.

**Comment by pixelzoom** [comment]
4affe22cb834760c3fff7d421bfca0e706c5cba3 has been cherry-picked into the 1.1 branch.

**Comment by ariel-phet** [comment]
Fix verified 1.2.0-dev.1.

**Comment by pixelzoom** [comment]
Ready for RC testing in https://github.com/phetsims/QA/issues/542.

**Comment by ariel-phet** [comment]
Fix verified in 1.1.0-rc2
