### ISSUE TITLE
Second sim not present in multi wrapper

### ISSUE THREAD

**Issue by liam-mulhall** [phetsims/natural-selection#266]
### Test Device

iPad Pro / MacBook Air

### Operating System

iPadOS 14.4.2 / macOS 11.2.3

### Browser

Safari 14.0.3 / Chrome 89.0.4389.114

### Problem Description

For https://github.com/phetsims/QA/issues/636. The second sim in the multi wrapper doesn't appear. See screenshot.

### Visuals

![issue](https://user-images.githubusercontent.com/60749003/114243159-586af900-9949-11eb-8489-1351444082c3.png)

**Comment by phet-steele** [comment]
The errors I get on Win 10 Chrome:

![image](https://user-images.githubusercontent.com/5863899/114243953-cebc2b00-994a-11eb-9f61-3c47fc2c601f.png)

**Comment by liam-mulhall** [comment]
I'm seeing the same errors on macOS Chrome.

**Comment by pixelzoom** [comment]
This looks like a job for the PhET-iO team! 🦸🏻‍♂️

**Comment by pixelzoom** [comment]
On Slack, I asked @kathy-phet about which issues are blocking. Related to this issue, she replied:
> https://github.com/phetsims/natural-selection/issues/266 - I will ask phet-io to look at this

**Comment by zepumph** [comment]
In https://github.com/phetsims/phet-io/issues/1733 we updated the way in which we compare apis, and added it as part of the built phet-io library/preload for our wrappers. 

@samreid,
In the above commit I made it so that it could gracefully support being overwritten, like in the multiwrapper when we import the library file two times. There is already a precedent for this in files like WrapperTypes, and PhetioIDUtils.

I also nested the global under `phetio`, because that is where globals go these days (same precedent in all our files). Especially look at PhetioIDUtils, as it is used in wrappers and as a preload in our sims.

@samreid please review.

**Comment by samreid** [comment]
I reviewed the change sets and tested in a built version of natural selection, and it all looks correct, thanks!  Since NS was a dev version, I don't think we need cherry-picking.  So perhaps this issue can be closed.

**Comment by pixelzoom** [comment]
I'm going to keep this open for verification by QA in RC testing.

**Comment by pixelzoom** [comment]
To verify this issue:

* Run the "Multi" wrapper, and verify that you see 2 instances of the sim, labeled "natural-selection 1" and "natural-selection 2".

**Comment by KatieWoe** [comment]
Looks good in rc.1
