### ISSUE TITLE
Missing updates in Client Guides

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/natural-selection#268]
For https://github.com/phetsims/QA/issues/636. In client requests there is a request to hide the generation clock. But the instructions provided do not match anything in studio.
<img width="560" alt="notinstudio" src="https://user-images.githubusercontent.com/41024075/114581794-4042f480-9c3d-11eb-8a04-daa18ff2200a.png">

**Comment by KatieWoe** [comment]
This also seems to happen for hiding the environmental buttons
<img width="628" alt="visiblenotinstudio" src="https://user-images.githubusercontent.com/41024075/114586550-07f1e500-9c42-11eb-9a8b-c54ea51052c7.png">

**Comment by pixelzoom** [comment]
Good catch.

It looks like files in phet-io-client-guides/natural-selection were not updated after adding `environmentPanel` to the tandem hierachy for for https://github.com/phetsims/natural-selection/issues/263. 

I've fixed client-requests.md in the above commits (@amanda-phet please review), and the revised tandems are:

```
naturalSelection.introScreen.view.environmentPanel.generationClockNode.visibleProperty
naturalSelection.labScreen.view.environmentPanel.generationClockNode.visibleProperty
naturalSelection.introScreen.view.environmentPanel.environmentRadioButtonGroup.visibleProperty
naturalSelection.labScreen.view.environmentPanel.environmentRadioButtonGroup.visibleProperty
```

It also looks like linked-property-example.png and studio-overview.png also need to be revised, since they show the part of the Studio treee that has changed.  I can't revise them because the assets used to create them are not checked in. (That appears to be general problem with all client guides, so I'll create an issue in phet-io-client-guides repo.)  @amanda-phet can you please revise these images with top priority?  (This is blocking the PhET-iO team from commiting some unrelated work to master.)

**Comment by amanda-phet** [comment]
I created these updated assets. If it's ok for me to commit them to master I can do that, but I wasn't sure so just putting them here for @pixelzoom. 

![linked-property-example](https://user-images.githubusercontent.com/7852916/114607368-b2293700-9c59-11eb-9a00-86d08f396d11.png)
<img width="936" alt="studio-overview" src="https://user-images.githubusercontent.com/7852916/114607379-b48b9100-9c59-11eb-8aa4-dca4b2f485c6.png">

**Comment by amanda-phet** [comment]
I see the revised tandems as well.

**Comment by pixelzoom** [comment]
@amanda-phet The files that you've included in https://github.com/phetsims/natural-selection/issues/268#issuecomment-818987577 have totally different than the dimensions of the files in GitHub.  Their resolution is significantly lower. Does that matter?

linked-property-example.png is 2880 x 1578, yours is 1531 x 840.
studio-overview.png is in the ballpark of 2720 x 1084 yours is 1872 x 752.

**Comment by pixelzoom** [comment]
@amanda-phet sent me another set of PNG files via Slack. The resolution is higher, but the dimensions are still off.  She checked with @arouinfar, and "there is no scientific process for creating the screenshots".  So we decided to go with these files, and I've commited them above. 

I tested by doing a local build, then inspecting the "PhET-iO Guide" and "Client Requests" links in the Wrapper Index.  I didn't see any problems. 

I'll labeled this a ready for QA verification.

**Comment by pixelzoom** [comment]
To verify this issue:

* In "Client Requests", check the modified tandem names shown in https://github.com/phetsims/natural-selection/issues/268#issuecomment-818903797.
* In "PhET-iO Guide", check the modified image files shown in https://github.com/phetsims/natural-selection/issues/268#issuecomment-818987577.

**Comment by KatieWoe** [comment]
Looks good in rc.1
