### ISSUE TITLE
Update screenshot in PhET-iO Guide.

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/natural-selection#273]
I came across https://github.com/phetsims/phet-io-client-guides/issues/11 and figured I would update the screenshot for this sim.

**Comment by amanda-phet** [comment]
Over to you @pixelzoom to review the change and flag for the next RC.

**Comment by pixelzoom** [comment]
Patched into the natural-selection-1.3 branch of phet-io-client-guides in the above commits. Labeling for verification in QA.

To verify:
1. Go to the Wrapper Index
2. Choose "PhET-iO Guide"
3. Scroll down to the "PhET-iO Studio Overview" section.
4. Verfiy that the screenshot shows label "Customize within Studio" with a capital "S" on "Studio".

**Comment by pixelzoom** [comment]
Since @amanda-phet will need to verify https://github.com/phetsims/natural-selection/issues/259 in the RC, she should probably verify this issue too.  Both issues are related to the same document, phet-io-guide.md.

**Comment by pixelzoom** [comment]
@amanda-phet This issue is ready for you to verify in [1.3.0-rc.2](https://phet-dev.colorado.edu/html/natural-selection/1.3.0-rc.2/phet-io/).   If everything looks OK, please check this issue off in https://github.com/phetsims/QA/issues/643.

High priority please, since the publication milestone is 4/30/21.

**Comment by amanda-phet** [comment]
Screenshots look good to me.
