### ISSUE TITLE
Population graph: scroll and zoom questions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#29]
I have many questions about the scroll (x-axis) and zoom (y-axis) controls on the _Population_ graph.

<img width="641" alt="screenshot_20" src="https://user-images.githubusercontent.com/3046552/70581443-73bace00-1b74-11ea-8733-acd1195def75.png">

Scroll (x axis, Generation)
- [x] What is the width of the x-axis? 7 generations, as in the mockups? (Java x-axis was "Time")
- [x] How much does the x-axis scale shift each time an arrow button is pressed? 1 generation?
- [x] Is the enabled state of the ">" (forward) button determined by the current generation number?  Or can the user scroll forward forever?
- [x] When the graph is scrolling, is "now" at the right edge of the graph, or do you want a bit of space between "now" and the right edge of the graph?

Zoom (y axis, Population)
- [x] What it the default y-axis scale? (Java is 0-50)
- [x] What is the min y-axis scale? (Java is 0-5)
- [x] What is the max y-axis scale? (Java is 0-5000, which seems large, since max bunnies is 1000)
- [x] What is y-max for each zoom level? (Java is 5, 15, 30, 50, 75, 100, 150, 200, 250, 350, 500, 1000, 2000, 3000, 5000)

**Comment by amanda-phet** [comment]
> Scroll (x axis, Generation)
> 
>  What is the width of the x-axis? 7 generations, as in the mockups? (Java x-axis was "Time")

I think 7 generations looks decent, but if you start implementing and you think it looks better to have fewer or more, we are flexible.
>  How much does the x-axis scale shift each time an arrow button is pressed? 1 generation?

Yes, we thought 1 generation made sense. I could see 0.5 generations also working here, if 1 full generation seems like too much. 
>  Is the enabled state of the ">" (forward) button determined by the current generation number? Or can the user scroll forward forever?

The forward button only becomes enabled when the data exceeds the width of the graph and there is data available to view. 
>  When the graph is scrolling, is "now" at the right edge of the graph, or do you want a bit of space between "now" and the right edge of the graph?

Our thought was "now" would be the right edge of the graph. 
> Zoom (y axis, Population)
> 
>  What it the default y-axis scale? (Java is 0-50)

0-50 seems fine. 
>  What is the min y-axis scale? (Java is 0-5)

0-5 seems fine. 
>  What is the max y-axis scale? (Java is 0-5000, which seems large, since max bunnies is 1000)

Max bunnies could be greater than 1000. If there are 900 bunnies, and then they mate, there will be ~2700 bunnies. At this point the sim will stop producing more bunnies (they have taken over the world) but we still need room to display those bunnies on the graph so the user can review the data. Is that math correct? If so, the max should probably be at least 4000.
>  What is y-max for each zoom level? (Java is 5, 15, 30, 50, 75, 100, 150, 200, 250, 350, 500, 1000, 2000, 3000, 5000)

I don't see a reason to change what was done in the java version, unless we want the max to be 4000 instead of 5000.

**Comment by pixelzoom** [comment]
> Max bunnies could be greater than 1000. If there are 900 bunnies, and then they mate, there will be ~2700 bunnies. 

I didn't realize that we let a full generation of mating play out before examining the number of bunnies.  I thought we stopped at 1000.   But as @amanda-phet pointed out, that's the way the Java version works.

12/12/19 design meeting:   Make it work like the Java version.  If there are performance problems with having 4000 bunnies, we will revisit.

**Comment by pixelzoom** [comment]
12/12/19 design meeting @amanda-phet @kathy-phet @ariel-phet @pixelzoom   

Make it work like the Java version.  If there are performance problems with having 4000 bunnies, we will revisit.

**Comment by pixelzoom** [comment]
Population graph scroll and zoom is working.   I deviated a bit from the above requirements:

* width is currently 5 generations, 7 seemed a little cramped

* Java zoom ranges seemed a little odd/cramped, so I improvised.  The HTML5 zoom ranges are currently [ 5, 14, 30, 50, 70, 100, 140, 200, 240, 350, 500, 1000, 2000, 3000, 5000 ].   And the tick spacing for each of those ranges is [ 1, 2, 5, 10, 10, 20, 20, 40, 40, 50, 100, 200, 400, 500, 1000 ].  

I made this very flexible, so we can easily adjust/tweak later.  So closing this issue.
