### ISSUE TITLE
Problem with generation spinner in Proportions chart

### ISSUE THREAD

**Issue by stemilymill** [phetsims/natural-selection#299]
**Test device**
Chromebook

**Operating System**
Chrome OS 90.0.4430.218

**Browser**
Chrome 90.0.4430.218 

**Problem description**
For https://github.com/phetsims/qa/issues/662
During a double string test, when the generation number reaches triple digits the beginning and end of the string get cut off by the generation scroll buttons in the proportions graph panel

**Steps to reproduce**
Select Intro screen
Establish a stable population  (for instance, brown fur dominant, wolves, limited food)
Select Proportions graph panel
Run simulation until it reaches the 100th generation

**Visuals**
![gen 100 g and 0 get cut off double stringtest](https://user-images.githubusercontent.com/85511101/124330707-fdb5f780-db5b-11eb-97e1-84e6a767012c.png)

Link to video (zoomed in more) https://drive.google.com/file/d/16kJ7xpcOb81HlC6Q8cpJbF9tPIMqPCDl/view?usp=sharing

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Natural Selection‬
URL: https://phet-dev.colorado.edu/html/natural-selection/1.4.0-rc.1/phet/natural-selection_all_phet.html
Version: 1.4.0-rc.1 2021-06-21 23:54:30 UTC
Features missing: applicationcache, csstransforms3d, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (X11; CrOS aarch64 13904.77.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.147 Safari/537.36
Language: en-US
Window: 1300x612
Pixel Ratio: 1.0499999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 96)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by pixelzoom** [comment]
This is a general problem with NumberSpinner -- it doesn't account for a dynamic range --  so I've reported it in https://github.com/phetsims/sun/issues/709.  

In Natural Selection, you can see how we gradually lose horizontal space as the generation number gains digits.  With 1 digit:

<img width="416" alt="screenshot_1045" src="https://user-images.githubusercontent.com/3046552/124500794-9f685f00-dd7d-11eb-89f1-bbece10e5a7f.png">

2 digits:

<img width="421" alt="screenshot_1046" src="https://user-images.githubusercontent.com/3046552/124500800-a3947c80-dd7d-11eb-84ee-99c5dca1fa37.png">

3 digits:

<img width="419" alt="screenshot_1044" src="https://user-images.githubusercontent.com/3046552/124500809-a7c09a00-dd7d-11eb-9a65-6c6db6ab724c.png">

It won't become a problem until we reach 1000.  That's the max generation, and the sim will then stop.

A couple of options for the 1.4 release, with estimates:

(1) Ignore this problem since (in pratice) it only occurs at 1000.  Estimate=0.
(2) Add more space horizontal space in sim-specific code, so it won't be a problem for 1000. Estimate = 20 minutes.
(3) Address the NumberSpinner issue, patch the release branch, etc.  Estimate = 3 hours.

@amanda-phet which option would you prefer?

**Comment by pixelzoom** [comment]
> (3) Address the NumberSpinner issue, patch the release branch, etc. Estimate = 3 hours.

I went with this option, because I thought of an easier way to address it.  By the time I finished patching the 1.4 release branch, it will probably have taken me 45 minutes.

**Comment by pixelzoom** [comment]
Patch in sun 'natural-selection-1.4' and natural-selection '1.4' branches.  

Ready for testing in next RC.

**Comment by pixelzoom** [comment]
To verify in RC testing:
1. Run the sim
2. Select Intro screen
3. Establish a stable population (for instance, brown fur dominant, wolves, limited food)
4. Select Proportions graph panel
5. Each time the Generation number gains a digit (e.g. 9 > 10, 99 > 100, 999 > 1000 ) you'll see that the space between the arrow buttons and "Generation {number}" remains constant, the arrow buttons move out a bit, and the control remains centered under the graph.

**Comment by KatieWoe** [comment]
Things look ok in rc.2
