### ISSUE TITLE
feedback on initial PhET-iO instrumentation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#30]
An initial pass at PhET-iO instrumentation was done, and can be test-driven in https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.17/phet-io/.  The sim's view is implemented, but the model is not.  So the instrumentation of the view is fairly complete, while the implementation of the model is relatively primitive/temporary. 

@amanda-phet and @kathy-phet are going to provide feedback, as part of their weekly meeting.  

What I'm most interested in is:

* Does the instrumentation satisfy the requirements marked as ✅ in the Natural Selection PhET-iO design document?
* Do the element names make sense? Are there any names that should be changed? 
* Does the structure of the tree make sense?  Is there anything that should be restructured? 
* I'm especially interested in the UI elements that are currently under `naturalSelection.labScreen.view.environmentDisplayNode`.  Does it makes sense to put these UI elements here because they are "inside" this area of the UI?   Or should they be moved up to `naturalSelection.labScreen.view`?

**Comment by pixelzoom** [comment]
Clarification: Please do not spend any time setting metadata (e.g. `phetioFeatured`) in Studio.  We'll do that sometime after the sim is feature-complete.

**Comment by amanda-phet** [comment]
@kathy-phet and I met today to review the PhET-iO instrumentation progress and have a few thoughts. I also made a few edits to the PhET-iO design doc where the name of a property had changed, simply because I noticed the discrepancy. Feel free to accept if they look right to you. 

**Model**

1. We noticed the checkbox state for wolves, limited food, and tough food use enabledProperty(eg. `naturalSelection.labScreen.model.environmentModel.wolves.enabledProperty`. It seems like enabledProperty is getting overloaded in its use. Could we remove the subfield and instead name these three properties something like `naturalSelection.labScreen.model.environmentModel.limitedFoodEnabledProperty`,  `naturalSelection.labScreen.model.environmentModel.limitedFoodOnProperty`,  `naturalSelection.labScreen.model.environmentModel.limitedFoodCheckedProperty`, or `naturalSelection.labScreen.model.environmentModel.limitedFoodVisibleProperty`? 

We noticed that the alleles checkbox property is named `naturalSelection.labScreen.model.pedigreeModel.earsAllelesVisibleProperty`. 

2. We are wondering if we should add something to the `pedigreeModel`, `populationModel`, and `proportionModel` names to indicate that they are in fact the displays. The term could be display, graph, chart, dataview, etc. We like display since it works well for all three. So, `naturalSelection.labScreen.model.pedigreeDisplayModel`, `naturalSelection.labScreen.model.populationDisplayModel`, and `naturalSelection.labScreen.model.proportionDisplayModel`. 

3. `naturalSelection.labScreen.model.populationModel.xMaximumProperty` should be labeled Has High Frequency Events = true. 

**View**
We partially got through this portion together, but I did my best to review the rest by myself. 

4. `naturalSelection.labScreen.view.environmentDisplayNode.environmentRadioButtonGroup` should probably include a link to the property `naturalSelection.labScreen.model.environmentModel.environmentProperty`. 

5. We also think the mutations selections panel `naturalSelection.labScreen.view.addMutationsPanel` should have links to the model property that identifies the mutation selection. This isn't currently in the tree yet, right? 

6. Depending on the final choice for (2) above, we should probably rename `naturalSelection.labScreen.view.graphsRadioButtonGroup` to `naturalSelection.labScreen.view.displayRadioButtonGroup` to be consistent.

7. I noticed that `naturalSelection.labScreen.view.pedigreeNode` has an `allelesPanel` and `graphNode`. `naturalSelection.labScreen.view.populationNode` and `naturalSelection.labScreen.view.proportionNode` only have `panel` and `graphNode`. Can we be more specific? Perhaps call them `legendPanel`?

**Comment by pixelzoom** [comment]
It will probably be most efficient/effective to discuss these face-to-face.  Happy to do that when you have time @amanda-phet.

**Comment by pixelzoom** [comment]
Since each item in https://github.com/phetsims/natural-selection/issues/30#issuecomment-566708654 seems like its own mini-discussion, I've moved each of them to a separate issue.  

I'll leave this issue open and assigned to @amanda-phet and @kathy-phet, since it sounds like they did not complete review of the "view" portion.

**Comment by pixelzoom** [comment]
If/when you resume review, here's a more current PhET-iO version:
https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.18/phet-io/

**Comment by pixelzoom** [comment]
12/19/19 design meeting: 

We reviewed the issues that came of this review.  We're going to pause review and do another pass (with a new issue) when more of the model is fleshed out.   Thanks for the review, and closing this issue.
