### ISSUE TITLE
Support random initial state values in the API file

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#302]
https://github.com/phetsims/phet-io/issues/1798 needs to be patched into the 1.4 branch.

There are many commits in https://github.com/phetsims/phet-io/issues/1798. @zepumph please provide an ordered list of shas to cherry-pick.

**Comment by zepumph** [comment]
From PhET-iO meeting, all that is needed to cherry-pick is this:

https://github.com/phetsims/chipper/commit/1b8852e3d76dd34280187c26eff1e02618906a49

All that is needed is to change the randomSeed to 332211.

Cherry pick likely won't work because it was put on top of other documentation changes from https://github.com/phetsims/phet-io/issues/1798

**Comment by pixelzoom** [comment]
I manually patch chipper "natural-selection-1.4" branch in https://github.com/phetsims/chipper/commit/38fcffc234ef4ee576b1ef47157632caee55a287.

Ready for testing in the next RC.

**Comment by pixelzoom** [comment]
@zepumph I'm not clear on how QA will verify this issue. Can you please add a comment with steps for verification?  Or if no verification is needed, please close this issue.

**Comment by zepumph** [comment]
I just spot checked this with the following steps:

```
pull-all.sh
cd natural-selection
grunt checkout-target --target=1.4
grunt --brands=phet-io
# copy natural-selection/build/phet-io/natural-selection-phet-io-api.json to clipboard
cd ../phet-io
git checkout master
# compare phet-io/api/natural-selection.json to clipboard
```

Every change in the diff comparison was explainable, and there were no variations in the random initialState values. Closing
