### ISSUE TITLE
Elements to make `phetioReadOnly: true`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/natural-selection#344]
For #323

@pixelzoom I've identified a few elements that should be `phetioReadOnly: true`.

There is no need for the client to control these Properties:
- [x] `model.bunnyCollection.deadBunnies.countsProperty`
- [x] `model.bunnyCollection.liveBunnies.countsProperty`
- [x] `model.bunnyCollection.recessiveMutants.countsProperty`
- [x] `model.graphs.proportionsModel.currentStartCountsProperty`
- [x] `view.graphs.populationNode.populationGraphNode.generationScroller.*Button.enabledProperty`

In the Pedigree Graph, it's possible to hide the allele checkboxes, but leave behind the legend information, which seems odd.
<img width="172" alt="image" src="https://github.com/phetsims/natural-selection/assets/8419308/96420936-8626-4444-9200-f8aa2db22963">

- [x] `view.graphs.pedigreeNode.allelesPanel.*Row.checkbox.visibleProperty`

**Comment by pixelzoom** [comment]
Done in the above commits. This was an API change, and required new migration rules.

For `view.graphs.pedigreeNode.allelesPanel.*Row.checkbox.visibleProperty`, I can think of no purpose to have this element if it's read-only.  So rather than make it read-only, I unistrumented `checkbox.visibleProperty`. @arouinfar let me know if you had a purpose for it, and I can certainly make it read-only. 

@arouinfar please review. Close OK.
