### ISSUE TITLE
French (fr) and Kinyarwanda (rw) translations lead to confusing data

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/natural-selection#357]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/968, the French translations for `lessThanValuePercent` and `valuePercent` have a ">"  symbol in front of them, instead of a "<" symbol and no symbol, respectively. This leads to data that doesn't make sense. 

**Visuals**
In sim:
<img width="788" alt="Screenshot 2023-08-07 at 2 08 51 PM" src="https://github.com/phetsims/natural-selection/assets/87318828/793a86b7-32ae-4248-8fc2-0b879f66f87f">

Here is what the French and Spanish translations look like for comparison:

<img width="684" alt="Screenshot 2023-08-07 at 2 23 42 PM" src="https://github.com/phetsims/natural-selection/assets/87318828/a2d6f9a8-1179-479a-bbf3-0ccb7cf660ae">

**Comment by Nancy-Salpepi** [comment]
I also see the same thing with the locale Kinyarwanda (rw).

**Comment by jbphet** [comment]
I'm wondering how to address this.  I can fix and republish the translations pretty quickly and easily, but then other translators might just make the same mistake.  Should we consider fixing up the string somehow so that this doesn't happen?  But we have other similar strings and they don't seem to get messed up like this (that I know of).  Why this one?  Just a fluke?

I'll probably just fix these and republish, then ping @oliver-phet to let the translators know that we had to manually fix their translations.

@oliver-phet - Do you have any thoughts on how to perhaps better handle this?

Also mentioning @pixelzoom, since he's the responsible dev for Natural Selection and might have a thought or two on the matter.

**Comment by oliver-phet** [comment]
> @oliver-phet - Do you have any thoughts on how to perhaps better handle this?

I personally don't think it's worth our effort to fix these unless the translator is unresponsive/no longer active. We should alert the credited translator about the issue and have them manually correct.

**Comment by pixelzoom** [comment]
I'm just about ready to publish 1.5.0-rc.2, so we need to decide what to do here ASAP.  My feeling is that we should decouple this from the 1.5 release, and address it separately.  If there hasn't been a decision by Monday 8/14, then I'll consider it decoupled. 

I don't care where a PhET developer fixes the strings, or whether we ask the credited translators to fix.  But the latter would be an opportunity for education, so that this doesn't happen again.

**Comment by jbphet** [comment]
No need to delay the release, as it doesn't impact source code for the sim.

@oliver-phet - Please notify the translators and let them fix it - I think it's a good approach so that they learn from it.  Please let me know if you need to know the specific translators that made the commits.

**Comment by oliver-phet** [comment]
Translator notified.

**Comment by pixelzoom** [comment]
@oliver-phet You said "Translator notified", singular.  Note that there are 2 locales that have been identified as having this problem: French (fr) and Kinyarwanda (rw), so you'll presumably need to notify 2 translators.

I looked through the babel files, and those appear to be the only locales with this problem.

**Comment by oliver-phet** [comment]
> @oliver-phet You said "Translator notified", singular. Note that there are 2 locales that have been identified as having this problem: French (fr) and Kinyarwanda (rw). So you'll presumably need to notify 2 translators.
> 
> I looked through the babel files, and those appear to be the only locales with this problem.

Whoops, I missed the comment that this also occurred in the Kinyarwanda translation (I'm going to update the issue title)! I've just emailed the Kinyarwanda translator about the mistake.

**Comment by pixelzoom** [comment]
@oliver-phet Do you have an update on this?  This issue has been open for a long time, would like to get it closed.

**Comment by oliver-phet** [comment]
No updates. I pinged both the French and Kinyarwanda translators on Feb 14, 2024 reminding them that the correction still hasn't been made. I'll ping again now.

**Comment by pixelzoom** [comment]
@oliver-phet Any reply from the translators?  If not, I'm going to close this issue.

**Comment by oliver-phet** [comment]
Thanks for the ping! The French translator corrected in https://github.com/phetsims/babel/commit/e6c645d2ae8692b8988cfae13f6baad3db882f10

No word from the Kinyarwanda translator. I think this issue is fine to close.
