### ISSUE TITLE
Is it OK to refer to alleles in the initial population as "mutant"? 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#79]
Related to https://github.com/phetsims/natural-selection/issues/9...

On 5/13/2020 in https://github.com/phetsims/natural-selection/issues/9#issuecomment-628081429, I expressed a couple of concerns about calling alleles in the initial population "mutations":

> I got partway through implementing this feature (completed the parser for the query parameters) and a couple of potential problems occurred to me:
> 
> (1) If a mutation (e.g. brown fur) is present in the initial population, can it really be considered to be a mutation? A mutation is an alteration of something that came before it. In the initial population (generation zero), there is nothing that came before it. If it's OK to still call it a mutation, great! If not, then this entire feature seems problematic.
> 
> (2) If bunnies in the initial population have alleles that we consider mutant (e.g. brown fur) should those bunnies be labeled with the "mutant" symbol in the Pedigree graph?
> Related to question (2) above...
> 
> And related to question (2)...
>
> If brown fur is recessive, and the initial population consists of 10 bunnies with genotype 'Ff', they contain the mutant allele, but their phenotype (appearance) is white fur. Since their genotype contains the mutant allele, should they be labeled with the "mutant" symbol in the Pedigree graph? Or should they be labeled with the "mutant" symbol only if the mutation appears in their phenotype? Either way, won't this be confusing?
> 
> When running the sim, we would never have a "first mutant" bunny that is "Ff" or "fF". When a mutation is first introduced, both of a bunny's alleles are set to the mutant allele, so that the mutation appears in the phenotype. (Java version did the same.) So a "first mutant" bunny will always be "FF" or "ff", depending on whether brown fur is dominant or recessive, and the phenotype would therefore always be brown fur.

At 5/14/2020 design meeting, we decided to proceed by not labeling bunnies in the initial population as "original mutants" (no mutation icon in the Pedigree graph).

@amanda-phet is going to consult with Megan (subject-matter expert) to make sure that we don't have a pedagogical problem.

**Comment by pixelzoom** [comment]
@amanda-phet Any response from Megan?

**Comment by amanda-phet** [comment]
Not yet. I just followed up with a dev version to illustrate the questions more clearly.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/natural-selection/issues/9#issuecomment-636050932, @amanda-phet said:

I did hear back from Megan about the other questions we had, and will post the emails in the design doc. 

1. It would be more accurate to replace the "Add Mutations" panel title with "Traits", but she said "if that goes beyond than just cutting-and-pasting terms into a program, it probably isn’t worth the hassle." 

2. It is just fine that we aren't labeling the mutant bunnies at mutants in the case that generation 0 has a starting population that includes mutants.

**Comment by pixelzoom** [comment]
@amanda-phet these responses confuse me, and I wish I had been included in the conversation with Megan. Could you please provide the questions that you asked Megan? (either here, or forward me the email?)

> 1. It would be more accurate to replace the "Add Mutations" panel title with "Traits", but she said "if that goes beyond than just cutting-and-pasting terms into a program, it probably isn’t worth the hassle."

I don't understand. Is Megan recommending to always title the panel "Traits", or only when mutation(s) have already been applied via a query parameter?  If the former, what if only one mutation has been applied via query parameters and the other 2 mutations can still applied by the user?

> 2. It is just fine that we aren't labeling the mutant bunnies at mutants in the case that generation 0 has a starting population that includes mutants.

This response confuses me.  Allele that exist in the original population are called normal (or wild) alleles.  A mutant allele is created when some allele that existed before it is changed (mutated).  There is nothing that exists before generation 0, so how can we have a mutant allele in generation 0? If there are 2 fur alleles in generation zero, then there were 2 normal (wild) alleles in the original population, not 1 normal allele and 1 mutation.  For someone trying to understand Mendelian genetics, these seems problematic. But if it doesn't bother Megan or anyone else, I'll drop it.

**Comment by pixelzoom** [comment]
Maybe my conceptual mistake is that I'm equating "generation 0" with "original population of the species".   If generation 0 is just any initial collection of individuals that we put together at the beginning of an experiment, then I can understand how generation 0 can contain both mutant and normal alleles.  @amanda-phet what is your understanding of "generation 0"?

**Comment by amanda-phet** [comment]
@pixelzoom and I cleared up my confusing choice of words. Here is the full text between me and Megan. In sum, we don't need to make any changes. 

I sent two emails and she responded to both, so the flow below is somewhat confusing, but I don't want to change any of her responses so you'll just have try to follow along. 

----- 
The sim will have the ability for a teacher to start it up with an initial population. This came from a client request to, say, start the sim with 50 white bunnies and 50 brown bunnies (rather than 1 white bunny). Since each bunny has a genotype, they would have to specify the distribution. For example: 50 Ff and 50 ff (and suppose brown fur is dominant).   

>This is a neat idea and allows for different sets of questions to be asked, which is a plus.

1. This brings up the question about brown fur being a mutation and how that should be represented in the sim. If brown and white bunnies are both present in the initial population, and there was no prior population to demonstrate inheritance of genes, can it really be considered a mutation? If that's ok, we don't need to change anything in the sim, but if not, that might be a problem. It would be challenging to change the "Add Mutations" panel or change language anywhere else in the sim. However if it's ok to continue calling brown fur a mutation, that's a relief. 

>As I said above, I think it would be good to change to “trait” but if that goes beyond than just cutting-and-pasting terms into a program, it probably isn’t worth the hassle.

 *Is it OK that we are still calling these "mutations" even though they already exist in the population?* 

>Good question.  I agree that we’ve moved a bit away from mutations.  What if we just called them “traits”?  That term can have slightly different meanings but, according to the National Human Genome Research Institute, it fits.   Alternatively, we could use “allele” but I like “trait” better.  Here’s another argument for stepping away from “mutations” as a term: this past semester, I still had some students thinking of mutations as something imposed on an organism by the environment and being able to “add a mutation” can support that misconception.  Perhaps if the user can “add a trait” but not add a “mutation” we can step away from that misconception.  Also, new alleles (traits) can enter a population by mutation and by immigration of new individuals, so this broadens the types of questions that could be asked of users (what are sources of new alleles in a population?). 

**Since we don't want to get into the game of trying to figure out when to call them mutations, and when to call them traits, we should leave the panel as-is.**

2. In the pedigree, we usually show an icon on the bunny with the mutation, so in this case should we indicate that all of the brown bunnies have the mutation, or that none of them have it? The way the model works, a mutation results in a genotype of either FF or ff, depending on whether the user selected dominant or recessive (this is a model simplification that we discussed last year). So, in the example I gave, saying a brown bunny that has heterozygous alleles really doesn't make sense! And if the mutation was recessive, Ff bunnies would be white, but would be considered the bunnies with the mutation. That seems incredibly confusing. 

>As mentioned above, I don’t think you need to identify the original bunnies – given the pedigree ability, you could see which ones are not originals (as they would have parents) and I don’t think it is a crucial piece of information anyway.

*Is it OK that none of the bunnies are labelled as being the original "mutant" bunny in the Pedigree (typically with the yellow DNA icon)? *

>I think it is fine that they are unlabeled. 

**No changes are needed with regards to the mutation icon**
