### ISSUE TITLE
inheritance model

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/natural-selection#97]
On 5/28/2020 in https://github.com/phetsims/natural-selection/issues/9#issuecomment-635633166, @kathy-phet said
>I played around with setting the initial population and watching the mating dynamics of the phenotypes. I think the science looks correct - and made me rethink things, but it makes sense. :) I sent if off to Megan to sanity check just the initial population setting and mating evolution of the phenotypes.

>Just asked her to play around with setting the initial state of the genetics of the bunny populations, and make sure phenotypes were evolving correctly (without any selection pressure). To have her expert eye on that part of the sim.

Email to Megan: 

>>If you had time, I wanted to have your sanity check on some of the numbers in the natural selection sim - to make sure the data jives with your prediction of what would happen.

>>If Amanda already asked you about this, just say so.

>>Right now, we have a version where you can set the initial population of bunnies and their alleles using query parameters - like so:
https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.44/phet/natural-selection_en_phet.html?introMutations=F&introPopulation=10FF,10ff
On the "Intro" screen this will play preset brown fur as dominant (F), and create a population of 10 bunnies with FF alleles and 10 white bunnies with ff alleles.

>>You can then watch the genetics evolve without selection factors turned on ... it basically seems to to go 75% brown phenotype and 25% which phenotype and doesn't really evolve after that. A part of me expected more and more brown bunnies, but I think I understand that you basically would end up with steady state of something like 25% FF, 50% Ff and 25% ff.

>>The "Proportions" graph is the best to watch this evolve.

>>Does this jive with your math of the situation and how it would evolve? Feel free to play around with the basic mating algorithms to make sure its looking good to you! In the initial population you can also specify Ff bunnies - I just did something simple. If you want to make brown recessive mutation, then do this introMutations=f instead of using the capital F.

>>Thanks for any feedback. No rush, but I hope you find it fun to play.

**Comment by pixelzoom** [comment]
FYI, here's how the model works, in both the Java and HTML5 versions.  The goal is to simulate Mendelian inheritance, where gametes are created by random segregation, and heterozygous individuals produce gametes with an equal frequency of their two alleles.

For each trait, a newborn bunny gets 2 alleles: 1 from the father, 1 from the mother.  Call them fatherAllele and motherAllele, respectively.

For each trait, a bunny has an array of alleles that looks like this, where `shuffle` puts the alleles in a random order:

```js
childAlleles = shuffle( [ fatherAllele, fatherAllele, motherAllele, motherAllele ] );
```

When a pair of bunnies mate, each bunny provides an allele from its `childAlleles` array.  And it cycles through this array _in order_.

**Comment by kathy-phet** [comment]
I don't fully understand the above model, Chris. What does the array childAlleles look like for the case of where just one trait fur is defined, and the if we have fur and ears defined? In particular, I'm not sure why there are two fatherAllele elements in childAlleles if the bunny only has 1 fatherAllele that it inherited from its father.

**Comment by pixelzoom** [comment]
I'm not sure what you mean by "one trait fur".  Fur, ears, and teeth are traits.  White fur and brown fur are genes.  

If you mean "what if there's only 1 gene for a trait"...  `childAlleles` array is still formed in the same way. fatherGene and motherGene will be identical, the bunny will be homozygous (both alleles the same), and they will always pass that allele on to their offspring, because it's the only allele that they have.  And that's the behavior for any homozygous individual, regardless of the gene pool.

If a bunny is heterozygous (alleles are different), then those alleles must be donated to offspring with equal frequency.  Choosing fatherAllele vs motherAllele using random number generation would eventually produce equal frequency, but possibly not for a very long time.  Putting 2 copies of each allele in the `childAlleles` and shuffling the array guarantees that we will immediately have equal frequency, with some degree of randomness.  If there was only 1 copy of each allele in `childAlleles`, we'd simply be alternating between the 2 alleles with no randomness.

This algorithm is taken directly from the Java version, where it is mostly undocumented.  And my only guidance so far has been to "make it behave like the Java version".  If you have a better suggestion for simulating Mendelian inheritance, I'm open to other suggestions.

**Comment by pixelzoom** [comment]
One other thing you should know about the inheritance model, which was also ported from the Java version.  

When a bunny is mutated, it is made homozygous - both of its alleles are set to the mutant allele.  This guarantees that the mutation will appear be reflected in the bunny's appearance (phenotype).  In reality, a mutation is a change in one of the inherited genes, not both.  I discussed this with @amanda-phet awhile back, and she verified that making the mutant homozygous is the desired behavior.

So for example, suppose that brown fur is applied as a recessive mutation.  The only fur allele in the gene pool would have been white fur, so the bunny will inherit 2 white fur alleles from it parents.  Then the mutation occurs.  If we mutated only 1 of the inherited alleles, then the mutant bunny would be white, because white fur is dominant and it would still have 1 white fur allele.  By mutating both alleles (making the bunny homozygous) whether the mutant allele is dominant or recessive is irrelevant, and the bunny's appearance will correspond to the mutant allele. 

And to clarify... This is for when a mutation first occurs.  After mutation has occurred, the mutant allele is just another gene in the gene pool, and subsequent matings use the `childAlleles` approach described above to determine the child's alleles.

**Comment by amanda-phet** [comment]
@pixelzoom that all sounds correct to me.

**Comment by pixelzoom** [comment]
Re inheritance... There's another way to look at the reason for why `childAlleles` contains 4 alleles (2 father, 2 mother) in random order.  Bunnies live to be 5 years old, so they mate 4 times.  So `childAlleles = shuffle( [ fatherAllele, fatherAllele, motherAllele, motherAllele ] )` guarantees that homozygous bunnies will donated their alleles to offspring with equal frequency, and in random order.

**Comment by pixelzoom** [comment]
In 6/11/2020 design meeting discussion of #98, I mentioned that mating 2 heterozygous recessive mutants could result in more than 1 offspring that has the mutation in the phenotype.  The team corrected me, and said that only 1 offspring would have the mutation in the phenotype.  Thinking about this more, I believe that I was correct.  And that there may be another aspect of the inheritance model that we need to discuss.

Here's a table that should possible outcomes of the current inheritance model (Java and HTML5):

| parent1 | parent2 | offspring |
| -- | -- | -- |
| FF | FF | FF, FF, FF, FF |
| ff | ff | ff, ff, ff, ff |
| FF | ff | Ff, Ff, Ff, Ff |
| FF | Ff | FF, FF, FF, Ft |
| Ff | Ff | FF, Ff, fF, ff *or* FF, FF, ff, ff |

If either parent is homozygous, there is 1 possible outcome.  But if both parents are heterozygous, there are 2 possible outcomes, as shown in the last line of the table.  In both outcomes, parents donate their alleles with equal frequency. Which outcome occurs depends on the random order in which the alleles are donated. 

According to Mendelian inheritance, heterozygous individuals produce gametes with an equal frequency of their two alleles. That does not guarantee that the offspring will include all possible combinations of the parents alleles.  If you are expecting all possible combination, that does not occur in the current model, or in reality.

**Comment by pixelzoom** [comment]
> ... If you are expecting all possible combinations, that does not occur in the current model - or in reality.

In reality, there are many other possible outcomes for 2 heterozygous parents (e.g. Ff):

```
Ft, Ft, Ft, Ft
Ft, FF, FF, FF
FF, FF, FF, ff
FF, FF, FF, FF
ff, ff, ff, ff
...
```

In reality, "parents donate their alleles with equal frequency" applies to the average over time.   But in this sim, it applies to each act of mating - which seems like a reasonable/necessary simplification.

**Comment by pixelzoom** [comment]
After more reading...  The Java model seems wrong to me, doesn't correspond to how meiosis occurs.  Shouldn't we be using a genetic cross, that corresponds to Mendel's Law of Segregation?   So Ff + Ff would have offspring FF, Ff, fF, ff.

**Comment by amanda-phet** [comment]
6/15/20 meeting: we will use a classic genetic cross, and stick with 4 offspring per 2 parents.

**Comment by pixelzoom** [comment]
Notes to self:

When implementing the genetic cross, be sure to adhere to all 3 of Mendel's laws:  Law of Dominance, Law of Segregation, and Law of Independence. Independence can likely be achieved by shuffling the cross for each trait before combining GenePairs into a Genotype.

**Comment by pixelzoom** [comment]
@amanda-phet Genetic cross (Punnett square) has been implemented in the above commits, and is ready for review.

The easiest way to review this is to use the query parameters to set an initial population, then inspect the first generation's genotype using the Pedigree graph. Start by verifying the behavior of one gene (e.g. Fur) with `?labMutations=F`.  Then try combinations of genes.

Below are the possible crosses for the fur gene.  Most of the outcomes are similar, just in different order as determined by the Punnett square (read in row-major order). Here's what the first line of the first table looks like as a Punnett square. Parent alleles are in bold, father alleles are along the left side, mother alleles are along the top.

| | F | f |
|--|--|--|
| **F** | FF | Ff |
| **f** | fF | ff |

Both parents heterozygous, same outcome in all cases:

| ?labPopulation | offspring |
| -- | -- |
| 2Ff | FF, Ff, fF, ff |
| 1Ff,1fF | Ff, FF, ff, fF |
| 1fF,1Ff | fF, ff, FF, Ff |
| 2fF | ff, fF, Ff, FF |

One parent heterozygous:

| ?labPopulation | offspring |
| -- | -- |
| 1FF,1Ff | FF, Ff, FF, Ff |
| 1FF,1fF | Ff, FF, Ff, FF |
| 1Ff,1FF | FF, FF, fF, fF |
| 1fF,1FF | fF, fF, FF, FF |
| 1ff,1Ff | fF, ff, fF, ff |
| 1ff,1fF | ff, fF, ff, fF |
| 1Ff,1ff | Ff, Ff, ff, ff |
| 1fF,1ff | ff, ff, Ff, Ff |

Both parents homozygous:

| ?labPopulation | offspring |
| -- | -- |
| 2FF | FF, FF, FF, FF | 
| 2ff | ff, ff, ff, ff |
| 1FF,1ff | Ff, Ff, Ff, Ff |
| 1ff,1FF | fF, fF, fF, fF |

**Comment by amanda-phet** [comment]
I am having trouble with the query parameter for some reason, but I can confirm that all of the tables above are correct. I would be happy to verify with the sim if I can get that query parameter to work, but I was able to verify a selection of bunnies after adding a mutation and they all looked correct.

**Comment by pixelzoom** [comment]
Which query parameter are you having trouble with? Example?

**Comment by amanda-phet** [comment]
https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.53/phet/natural-selection_en_phet.html?secondsPerGeneration=2&labMutations=F&labPopulation=1 

Getting this error dialog
![image](https://user-images.githubusercontent.com/7852916/84962376-f1cbd480-b0c3-11ea-9c12-e1443bff3f6c.png)

It's just confusing because you suggested using `labMutations=F` and I confirmed that I spelled it correctly.. can't figure out what I'm doing wrong!

**Comment by pixelzoom** [comment]
If you have `labMutations` set, then `labPopulation` must include at least one count and genotype, e.g. "1FF".   The values that I put in the `?labPopulation` column of the tables are the values that you should be using for that query parameter.

**Comment by pixelzoom** [comment]
You can also run with `?log` and see more detailed error messages in the browser console.

**Comment by amanda-phet** [comment]
Thanks, I feel silly for not realizing that's where I made the mistake. 

All of the mating seems to be working as specified above.
